{% set name = "cmakelint" %}
{% set version = "1.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87079ff6bb74bc961522aef64dedf2aeb90a8152718eabe105f1f261451b7329

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - cmakelint = cmakelint.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - pytest-runner
  imports:
    - cmakelint
  commands:
    - cmakelint --version

about:
  home: https://github.com/cmake-lint/cmake-lint
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Static code checker for CMake files
  dev_url: https://github.com/cmake-lint/cmake-lint

extra:
  recipe-maintainers:
    - asafkahlon
    - timkpaine
